home: # 展示页的配置可跳过，详见<https://revealjs.com/>
  append_to_section_tag:
    - key: data-markdown
    - key: data-separator # 水平展示页分隔符
      value: <!-- .slide -->
    - key: data-separator-vertical # 垂直展示页分隔符
      value: <!-- .slide vertical=true -->
    - key: data-background-color
      value: "White"
  prepend: |
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.4.0/dist/reveal.min.css,npm/reveal.js@4.4.0/dist/theme/serif.min.css"
    />
    <style>
      .sidebar {
        line-height: 1.5;
      }
      .reveal .slides {
        text-align: left;
      }
      .reveal a,
      .reveal a:hover,
      .reveal a:focus {
        color: inherit;
        border-bottom: 1px solid var(--theme-base-color);
      }
    </style>
  append: |
    <script
      async="async"
      src="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.4.0/dist/reveal.min.js,npm/reveal.js@4.4.0/plugin/markdown/markdown.min.js,npm/reveal.js@4.4.0/plugin/math/math.min.js"
      onload="
      for(let x of document.getElementsByClassName('wrap'))
        x.classList.add('reveal');
      Reveal.initialize({
        height: '100%',
        mouseWheel: true,
        navigationMode: 'linear',
        plugins: [ RevealMarkdown,RevealMath.KaTeX ]
      });
    "></script>
